name = "st-franz-pavillion"
type = "javascript"

account_id = "enourmouz"
workers_dev = true
compatibility_date = "2024-06-01"

[site]
bucket = "./dist"
entry-point = "."

[build]
upload.format = "modules"
